name: sample_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
# Riverpo関係
  flutter_riverpod:
  riverpod_annotation:
  freezed_annotation:

  csv: ^5.0.0
  youtube_player_iframe: 
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.0.2
  flutter_form_builder: ^9.3.0
  go_router: ^14.8.1

  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
# Riverpod関係
  build_runner:
  freezed:
  riverpod_generator:
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/csv/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"